# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexander Chepurnoy
title: Money Systems Hacker
email: kushti@protonmail.ch
website: ergoplatform.org

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: chepurnoy
github_username:  kushti
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Alexander Chepurnoy (aka kushti) and I'm doing cryptocurrency related development since 2013. Since 2017 I am Ergo core developer.

  My interests: <mark>monetary theories</mark>, <mark>cryptography</mark>, <mark>peer-to-peer systems</mark>

content:
  - title: Cryptocurrency-Related Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ergo
        link: github.com/ergoplatform
        # link_text: Project Website
        caption: June 2017 - Present
        additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Smart money for the people, mineable from home.
        description: | # this will include new lines to allow paragraphs
          Proof-of-work cryptocurrency with unique kind contracts in extended UTXO model made with monetary systems development support in mind, also supporting Sigma-protocols based cryptographic applications. A lot of decentralized and peer-to-peer financial applications already exists, such as decentralized exchanges, stablecoins, p2p auctions, bonds, financial games (HodlCoin, AuctionCoin), monetary systems (ChainCash), etc. Still no ASICS, so mine it with GPUs. 
          I have made like half of all the core development here. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Input-Output Global
        link: iohk.io
        # link_text: boringcompany.com
        sub_title: Research Fellow
        caption: February 2016 - 2020
        quote: >
          Solving hard problems in the cryptocurrency space by solid research
        description: | # this will include new lines to allow paragraphs
            Worked on different R&D projects and made a lot of papers.
      - layout: left
        title: SmartContract.com
        link: SmartContract.com
        # link_text: boringcompany.com
        sub_title: Cofounder, systems architect, backend developer
        caption: October 2014 - December 2015
        quote: >
          Getting consensus on physical events, with automated cryptocurrency payments 
        description: | # this will include new lines to allow paragraphs
            Worked on different R&D projects and made a lot of papers.  
      - layout: left
        title: Nxt cryptocurrency
        link: https://www.jelurida.com/nxt
        # link_text: boringcompany.com
        sub_title: Core developer
        caption: May 2014 - October 2015
        quote: >
          First pure Proof-of-Stake cryptocurrency
        description: | # this will include new lines to allow paragraphs
            NXT was first pure proof-of-stake cryprocurrency, CoinMarketCap top-3 by capitalization back in June 2014. I made some new features there, and started doing tests. 


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Before cryptocurrencies I worked as software developer since 2006 in different companies and the as a freelancer, in the fields of database management software, web applications, distributed data harvesting and processing. Graduated from Saint-Petersburg University of Information Technology, Mechanics and Optics (ITMO). Read a course in cryptography there twice, in 2018 and 2020.
      
      There were some cryptocurrency-related projects I made back in 2013 (before Nxt), such as one of the first CEX prices aggregators, backend for a Bitcoin wallet etc. 


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
